apiVersion: apps/v1
kind: Deployment
metadata:
  name: jgj-deployment
  labels:
    app: jgj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jgj
  template:
    metadata:
      labels:
        app: jgj
    spec:
      containers:
        - name: jgj
          image: maciejgum/java-github-jenkins:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080