apiVersion: v1
kind: Service
metadata:
  name: java-github-jenkins-service
spec :
  type: NodePort
  selector:
    app: java-github-jenkins
  ports:
  - port: 80
    targetPort: http
    nodePort: 30000
    name: http
  - port: 5701
    name: hazelcast
  
